---
- hosts: localhost
  vars_files:
    - ../../group_vars/all
  tasks:
    - name: Get disks
      virtualDisk:
        login:
          unityIP: "{{ unity_host }}"
          username: "{{ unity_username }}"
          password: "{{ unity_password }}"
        get:
         fields: id
      register: result1
    - debug: var=result1['output']

