---
- hosts: localhost
  tasks:
    - name: ESRS
      dellemc_unity:
        unity_hostname: "10.245.16.171"
        unity_username: admin
        unity_password: Password123!
        unity_updates:
          - {resource_type: systemInformation, id: '0', contactFirstName: 'Jiale', contactLastName: 'Huo', locationName: 'CloudLink', contactEmail: 'jiale.huo@emc.com', contactPhone: '123-456-7890'}
          # - {resource_type: esrsParam, id: '0', action: checkNetwork}
          # - {resource_type: esrsParam, id: '0', action: requestAccessCode}
          # - {resource_type: esrsParam, id: '0', action: getAvailableSites, accessCode : "243857"}
          # - {resource_type: esrsParam, id: '0', "siteId" : "324546"}
        unity_queries:
          - {resource_type: esrsParam, fields: 'enabled,isCentralized,status, statusDescription::@enum(status)'}
      register: result
    - debug: var=result
