---
- hosts: localhost
  tasks:
    - name: Updates and queries
      dellemc_unity:
        unity_hostname: "192.168.0.200"
        unity_username: admin
        unity_password: Password123!
        unity_updates:
          - {resource_type: user, name: test1, password: Welcome1!, role: administrator}
          # - {resource_type: user, id: 'user_test1', role: 'operator'}
          - {resource_type: remoteSyslog, id: '0', enabled: True, address: '192.168.0.11:515', protocol: 1, facility: 0}
          - {resource_type: dnsServer, id: '0', addresses: [10.254.66.23, 10.254.66.24]}
          # - {resource_type: ntpServer, id: '0', addresses: [10.254.140.21, 10.254.140.22], rebootPrivilege: 2}
          # - {resource_type: user, id: 'user_test1', action: 'delete'}
        unity_password_updates:
          # - {username: test1, password: Welcome1!, new_password: Welcome2!}
        unity_queries:
          # - {resource_type: user, id: 'user_test1', fields: 'role.id'}
          - {resource_type: remoteSyslog, id: "0", fields: 'address,protocol,facility,enabled'}      # id parameter has to be of the string type
          - {resource_type: dnsServer, fields: "domain, addresses, origin", page: 1, per_page: 100}
          # - {resource_type: ntpServer, id: "0", fields: addresses}      # id parameter has to be of the string type
      register: result
    - debug: var=result
